---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---


Welcome to the Acral Melanoma Ulceration website. This repository contains the code and tools required to reproduce the results from the manuscript *"The microenvironment of ulcerated acral melanoma is characterised by an inflammatory milieu and an enhanced humoural immune response"*. 

# Content

This repository includes R Markdown documents with step-by-step analyses, processed datasets, functions for data processing, and generated figures. Navigate through the following items:


* [Figure 1. Clinical characteristics of acral melanoma patients according to ulceration status](figure1_clinical.html)

* [Figure 2. Transcriptional characterisation of acral melanoma tumors](figure2_DE.html)

* [Figure 2. GSEA analysis](figure2_GSEA.html)

* [Figure 2. Transcription Factor activity inference](figure2_TF.html)

* [Figure 3. Immune Cell Type Composition](figure3_deconvolution.html)

* Figure 3. Proteomic Analyses

